---
slug: softcover-cheat
filename: softcover-cheat
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 04170257-f5fb-4efd-adca-49301cca206c
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
